name: pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cópia os arquivos do repositório
        uses: actions/checkout@v5

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name : Executar a lintagem
        run: poetry run task lint

      - name: Executar os testes
        run: poetry run task test

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      ACCESS_TOKEN_EXPIRE_MIN: ${{secrets.ACCESS_TOKEN_EXPIRE_MIN}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}